### ISSUE TITLE
[Select] highlight inconsistencies with native select

### ISSUE THREAD

**Issue by chasestarr** [uber/baseweb#1998]
reproducing codesandbox: https://codesandbox.io/s/select-similar-to-native-select-6mwuq

'highlighted' - indicates mouse hover/keyboard navigation target.
'selected' - the visual equivalent of the option specified by the component's 'value' prop.

## Current Behavior

On dropdown open, the 'highlighted' option begins with the first option no matter if there is a 'selected' option or not.

## Expected Behavior

On dropdown open, the 'highlighted' option should begin with the 'selected' option if present else it should highlight the first option.

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.6.2  |

- [x] I have searched the [issues](https://github.com/uber-web/baseui/issues) of this repository and believe that this is not a duplicate.

**Comment by gergelyke** [comment]
Did a quick investigation - it seems like the `highlighted ` prop is coming from the `Menu` component

**Comment by ashish-kale** [comment]
@chasestarr @gergelyke Can you check https://github.com/uber-web/baseui/pull/2004 for this ? Also, I am unable to add label to it, can you please add it?

**Comment by chasestarr** [comment]
Thank you @ashish-kale - PR merged and will be included in the next release

**Comment by BenjaminFrench** [comment]
@ashish-kale @chasestarr 
I am experiencing what I believe to be incorrect highlight behavior with select when multi prop is enabled. This behavior can be observed at https://baseweb.design/components/select/#select-as-multi-pick-search

The first time I click in the select component, the dropdown renders and the first option is highlighted. The next time I click in the input, and subsequent clicks, nothing is highlighted. This appears to be due to getHighlightedIndex in src/select/dropdown.js returning -1 instead of 0. 
```js
  getHighlightedIndex = () => {
    const {value, options, valueKey} = this.props;
    // Highlight only first value as menu supports only a single highlight index
    let firstValue: OptionT = {};

    if (Array.isArray(value) && value.length > 0) {
      firstValue = value[0];
    } else if (!(value instanceof Array)) {
      firstValue = value;
    }

    if (Object.keys(firstValue).length > 0) {
      const a = options.findIndex(
        option => option && option[valueKey] === firstValue[valueKey],
      );
      return a || 0;  // returns -1 when a = -1 because -1 is falsy
    }
    return 0;
  };
```

Seems like the intention here was to return 0 and not -1.

**Comment by ashish-kale** [comment]
@BenjaminFrench I am not able to reproduce the issue in the link you sent, because in it the option which is selected is removed from the dropdown, which leaves nothing to highlight there. Can you sent a codesandbox link if you have can exactly repro the issue?

**Comment by BenjaminFrench** [comment]
@ashish-kale 
Here is a codesandbox https://codesandbox.io/s/select-ojeth?fontsize=14&hidenavigation=1&theme=dark

To reproduce:
1. Click inside select component. Option 'AliceBlue' is highlighted - this is correct
2. Select option 'AliceBlue'. Dropdown menu disappears.
3. Click inside select component again. Now there is no option highlighted. Option 'AntiqueWhite' should be highlighted.   getHighlightedIndex() is returning -1 in this case.

Perhaps this is the intended behavior, but it seems like we would want to highlight the first option in this case. Not having anything highlighted means the user needs to either use the mouse or an extra keystroke (down arrow followed by enter key) to select an option. If the first option was highlighted they could just press enter to select.

Why this is an issue is more apparent with a Select with **creatable** and **multi** props. Here is another sandbox to demonstrate: https://codesandbox.io/s/select-creatable-multi-pick-o8flu?fontsize=14&hidenavigation=1&theme=dark

For this one, to reproduce:
1. Click inside select component and type "Chicago".
2. "Chicago" is highlighted and I can press Enter key to select.
3. Input remains focused and I can type "Denver", but this time "Denver" is not highlighted, and in order to select it, I need to first press down arrow key and then enter.

For my use case, I would like users to be able to continue typing in options and only have to press enter to select/create the option. Currently the extra down arrow keystroke to highlight is poor experience for my users.

**Comment by houmark** [comment]
For what it's worth, I agree with @BenjaminFrench's expected behavior.

**Comment by chasestarr** [comment]
reopening since it looks like there are some unresolved issues

**Comment by ashish-kale** [comment]
@BenjaminFrench @houmark @chasestarr raised PR for this
