### ISSUE TITLE
Add ability to de-duplicate toaster notifications

### ISSUE THREAD

**Issue by jcready** [uber/baseweb#2333]
The `toaster` export from `"baseui/toast"` is **very** handy. I was wondering if it might be possible to provide the ability to de-duplicate the toaster notifications such that I could prevent multiple "toast" notifications appearing with the same content and also allow me to update the properties of said notification. I imagine adding an optional `id` (or possibly use the existing `key` property) to the options object which if the `toaster` saw an `id` value which matched one of the currently visible "toast" notifications, it would not create an additional notification. Instead it would ideally update the existing notification with the new properties (e.g. replace the children, reset the `autoHideDuration` and timeout, etc.).

I understand that there is already `toaster.update(key, {options})`, but it is fairly tedious to keep track of which notifications are currently visible and use that info to switch between, say `toaster.update()` and `toaster.info()`.

**Comment by foodforarabbit** [comment]
I can help out with this feature.

I think it should work the way you think it should anyway, since popping up multiple toasts with the same key causes odd behavior (e.g. in the documentation, clicking "show more" for one toast updates all of them, closing one toast causes them all to disappear) and also might cause other issues (e.g. the Toast element uses the toast `key` property as the `key` prop, so you would have multiple sibling react nodes with the same key which *used* to cause warnings / errors, although none popped up for me).

So to clarify the changes I intend to make: 
you can set `key` as toast property (already exists)
when trying to show a toast, it will check the existing toasts for similar keys and if found, update instead. Otherwise, proceed as it does currently (show a toast = `.info()`, `.positive()`, `.warning()`, `.negative()` etc...
when updating a toast, it should also reset the autohide timer (currently it doesn't, even with `.update()`). There are two ways to do this:
a) It will simply call Toast.clearTimeout() and then Toast.startTimeout(), simulating an "onMouseEnter" and then an "onMouseLeave". This will also reset animateIn and animateOut timers... 
b) only stop the autohideTimeout and then restarting it, which simply restarts the timer for autohiding. This seems like the safer way. We could modify startTimeout() to do that automatically (stop any existing autohideTimeout)

I'll submit a PR for method b) and we can make changes to it as needed
