### ISSUE TITLE
[DataTable] - exportable Filter and/or Editable components

### ISSUE THREAD

**Issue by dpenny** [uber/baseweb#2377]
# Feature description
My application has 'List Tables' for managing social media campaigns across various platforms.  

For example, we have a table representing campaigns in twitter with various fields - ie each row is a twitter campaign, and each column is a field such as campaign name, status, budget, etc.  

We want some of these fields to be editable inline. 

We currently have a custom `DataTable` component (uses `baseui/table` ), and a custom `ListFilters` component to filter the table by various fields. The `ListFilters` has almost identical functionality to `FilterMenu` component in baseUI's `Data-Table`. It would be great to be able to use this component, and/or be able to use `Data-Table` with the option to override and create editable fields. 

Thank you!

**Comment by chasestarr** [comment]
My concern is that it may be troublesome to transform your row/column data into the format that the `FilterMenu` expects, since it is tightly coupled to the `DataTable`. You can test it out by importing the `FilterMenu` from `baseui/data-table/filter-menu.js`, but we don't follow semantic versioning on file-level imports. Let me know how it goes and then we can consider exporting it at the directory level

**Comment by gergelyke** [comment]
@dpenny is this something you still need?

**Comment by gergelyke** [comment]
Closing this one - please reopen if you still need this feature
