### ISSUE TITLE
[ThemeProvider][BaseProvider] Popover mounts new divs to end of body element

### ISSUE THREAD

**Issue by chasestarr** [uber/baseweb#2513]
If an application does not use the `BaseProvider`, `Popover` portaling will leave behind an empty div. What are some ways that baseui can warn developers that `BaseProvider` is missing?

**Comment by chasestarr** [comment]
Adding an warning to `ThemeProvider` may not be the right way to go because there are legitimate use-cases to use that separate from `BaseProvider`. Maybe warn if the `Layer` component fails to find the `BaseProvider`?

**Comment by foodforarabbit** [comment]
Yea I think adding a warning to Layer makes sense, it could warn about missing LayersManager or BaseProvider, depending on which way you want to push people towards.

We already check for `host` in Layer in order to switch between the host component and the document.body for inserting the divs, so in that same place we could console.warn about the missing Provider if no host is detected.

I can make a sample PR for this
