### ISSUE TITLE
[table] allow data to be an array of objects

### ISSUE THREAD

**Issue by mraines4** [uber/baseweb#2527]
It looks like the data only takes an array of objects and the column headers only takes an array of strings.
## Feature description
Is there any way to pass in an array of objects (as in a response from an api request) and use the keys as the column headers and the objects as data rows?

**Comment by chasestarr** [comment]
Hi @mraines4 this component was designed to be as simple as possible and because of that there is no key indexing API to learn. Your application can transform the data however you prefer before passing it to the table component. You could consider building a function that does the mapping from object to rows/columns yourself.
