### ISSUE TITLE
[Button] height changes between loading/not loading states

### ISSUE THREAD

**Issue by chasestarr** [uber/baseweb#2837]
Latest baseui release. Related to https://github.com/uber/baseweb/pull/2821#issuecomment-584880396. It can be reproduced by changing the size prop on Button doc page and then toggling the loading state.

**Comment by chasestarr** [comment]
@houmark Thanks for raising the issue. A fix has been published in v9.52.2

**Comment by houmark** [comment]
I'm sorry @chasestarr — but I'm still seeing the same height change with v9.52.2 for both a large button and a default-sized button. This may again be due to overrides or a different font-size or something. I'll test more tonight and provide more feedback.

Having said that, I'm not sure the fix with different `sizing.scale` is the safest solution, but I may not understand it well enough. Another option would be to measure the height of the button on the normal state, save it in memory, and then set that height when in the loading state?

**Comment by chasestarr** [comment]
I can't reproduce on our docs site editor, but good point about overrides. If button font size has been overridden, it will continue to change height. Is that what you have going on in your application?

**Comment by houmark** [comment]
No, we don't have any font sizes changes, our theme tweaks are only colors and media breakpoints.

I've narrowed it down to a global style we have:

```
div {
  box-sizing: border-box;
}
```

This should not really break anything and while this one may be obtrusive, it's also "normal" practice to have this style in modern applications. If we drop that style, then most of our design breaks. Maybe this is simply missing in the div's for the spinner / button?

**Comment by houmark** [comment]
I think this change is gonna create a lot of problems. Maybe this should be reverted until a proper solution that as sensible can be thought out.

This is a Code Sandbox, forked from the documentation site, and no other modifications has been done than a quick and dirty loading state change:
https://codesandbox.io/s/button-zvifg

Note how the button sizes down when loading. This may be due to missing Baseweb components surrounding the button, but shouldn't each component be stable on its own?

**Comment by houmark** [comment]
I've now added the border-box CSS style in index.html and the button is resizing its height when the loading state changes.

**Comment by houmark** [comment]
I did a "hot patch" on our CSS to be like this, which fixed the height changes on buttons when `isLoading` is true:

```
div {
  box-sizing: border-box;
}
button div {
  box-sizing: unset;
}
```

Baseweb should maybe handle that?

I think a better long term solution is a ref on the button to measure the height and keeping that exact height while loading, though I am not sure if different box-sizing will still affect that, though it should be possible to reset that and make a combination of the two.

I'm pretty sure we are not the only ones running `box-sizing: border-box` for our global app in order to simplify widths of div's with borders.

**Comment by chasestarr** [comment]
Applying global styles to elements is not something we can sustainably support, but I'm happy to push a fix for this particular situation

**Comment by houmark** [comment]
Maybe you misunderstood me. My main purpose is that the button is not sensible to common inherited global CSS styles like `box-sizing`, not to be too opinionated about how CSS needs to be done in order for it to work.

I'll test the fix once released and report back!

And just for the record, it's not semantically correct to have a `div` inside a `button` so fixing that may be a good idea and would have the side effect of fixing this issue as well.

Ref: http://validator.w3.org/#validate_by_input+with_options

Try:
```
<!DOCTYPE html>
<html lang="en">
<head><title>Test</title></head>
<button><div></div></button>
</html>
```

Notice the error:

> Error: Element div not allowed as child of element button in this context. (Suppressing further errors from this subtree.)

**Comment by houmark** [comment]
`span` is semantically correct, so replacing the spinner to be a span when inside a button (and maybe also in other tags that does not allow a child div) may be a good solution. I don't think there should be any issues with making the span act as a div for the spinner.

**Comment by chasestarr** [comment]
Sure, pushed a commit with it as a span

**Comment by houmark** [comment]
Great, I was thinking that just making it a span in all situations could work.

I'll test and report back!
