### ISSUE TITLE
[Step] component unmounts Description component when Parent state changes.

### ISSUE THREAD

**Issue by YashGadle** [uber/baseweb#3048]
Reproduce here - https://codesandbox.io/s/react-example-zq8mv

## Current Behavior
When rendering content inside a `Step` component using renderProp `Description` (inside `overrides`), the content is always unmounted when parent's state changes.
If we render an `input` inside a `Step` and then try to enter the text it would unmount and then rerender with empty text.

## Expected Behavior
It should not destroy the rendered component instead update it.

## Your Environment
Dev

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.54.0  |
| React   |   v16.13.0      |
| browser |   Chrome (80.0.3987.132 (Official Build) (64-bit))      |

Also reproducable with latest version of baseui.

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by tajo** [comment]
@YashGadle Thanks for a great repro.

There is a problem with our overrides implementation. We dynamically combine override values and create components inside of the `render()` function of parent component (in this case `Step`). So it changes with any state update and gets remounted. That causes issues similar to yours.

There is no quick fix like applying `React.useMemo` but rather re-implementing the whole thing. We have some ideas and hopefully it should not break anything. We will also need to make changes in all components. So this make take a while.

**Comment by chasestarr** [comment]
Hi @YashGadle I was not able to make this 'just work', but linked below is a recommendation to resolve. The problem comes from in-lining the override component. When the parent updates and re-renders, it creates a new component there. You'll need to provide a function that has referential equality to the previous render.

[example](https://github.com/uber/baseweb/pull/3153/files?file-filters%5B%5D=.js#diff-5e4381daf5cdf21b8b0a9db8cfe36b38R36-R56)

**Comment by chasestarr** [comment]
Closing this issue. Please review the linked example above for how to avoid the remount
