### ISSUE TITLE
Functional props override with ListItemAnchor breaks link

### ISSUE THREAD

**Issue by sandgraham** [uber/baseweb#3103]
https://codesandbox.io/s/menu-anchor-overrides-props-function-bug-7rswb

When you use the functional props override with Menu's `ListItemAnchor` the link becomes un-clickable. If you change to the object form of props override things work as expected.

[Current work around](https://codesandbox.io/s/temp-fix-for-props-override-on-menu-anchor-0vlq6) if you really need dynamic props is to use the component level override.

**Comment by chasestarr** [comment]
The problem is that when we have a prop function, we dynamically create an HOC component in the `getOverrides` function. Whenever the component re-renders, it unmounts/mounts the component leading to the click event no longer having an associated dom element. Fixing this will require a significant refactor of how overrides work internally. It all comes down to how we instantiate override components in render, rather than statically creating the HOC. I've prototyped a solution below, but have not ironed out the edge cases

```js
// overrides.js
import {isValidElementType} from 'react-is';
function Override(Base) {
  const Result = React.forwardRef((allProps, ref) => {
    const {override, ...props} = allProps;
    if (!override) {
      return <Base ref={ref} {...props} />;
    }

    if (isValidElementType(override)) {
      const ComponentOverride = override;
      return <ComponentOverride ref={ref} {...props} />;
    }

    if (typeof override === 'object') {
      let Component = Base;
      if (isValidElementType(override.component)) {
        Component = override.component;
      }

      let overrideProps = {};
      if (typeof override.props === 'object') {
        overrideProps = override.props;
      } else if (typeof override.props === 'function') {
        overrideProps = override.props(props);
      }

      if (override.style) {
        overrideProps.$style = override.style;
      }

      return <Component ref={ref} {...overrideProps} />;
    }

    return <Base ref={ref} {...props} />;
  });

  return Result;
}
```

```js
// component.js
import {Override} from 'overrides.js';
const BaseComponent = Override(StyledBaseComponent);
function Parent(props) {
  return <BaseComponent override={props.override.BaseComponent} />
}
```

**Comment by sandgraham** [comment]
Oh I really like this.

**Comment by chasestarr** [comment]
We deprecated the ability to pass dynamic props function to overrides
