### ISSUE TITLE
bui generation results in mismatches with repeated renders

### ISSUE THREAD

**Issue by phou87** [uber/baseweb#3126]
The code in https://github.com/uber/baseweb/blame/master/src/utils/get-bui-id.js uses a global counter to provide a somewhat stable method of generating ID's. However, this does not work beyond the first time that the server renders something because the counter does not get reset for subsequent renders. Thus, you will ALWAYS have mismatches after the first time.

I don't have a great solution for this since as mentioned, it's a hard problem, but at the very least you may as well generate random ID's so as to not trick people into thinking it should match.

**Comment by tajo** [comment]
It seems there is no good solution for this right now. If you run into this problem, you should always be able to set these IDs manually. 

> you may as well generate random ID

This would always fail when using SSR with

> Warning: prop `id` did not match. Server: "Checkbox:..." Client: "Checkbox:...."

The problem is described/discussed in this [rfc](https://github.com/reactjs/rfcs/pull/32). Fortunately, somebody has stared implementing this: https://github.com/facebook/react/pull/17322

So it's probably best to wait for the official support.
