### ISSUE TITLE
Theme context of consumer different from theme context of parent provider

### ISSUE THREAD

**Issue by jasonbarone** [uber/baseweb#3127]
## Current Behavior
I'm currently experiencing unusual behavior where the ThemeProvider theme is not the same as the theme argument in a ThemeContext.Consumer or ThemeConsumer. The theme argument returns a LightTheme as opposed to what is in your Provider. The following sandbox has an example: https://codesandbox.io/s/basic-usage-j7t0l

To see the issue:
1. Observe the theme in index.js (LightThemeMove).
2. Review the console.log in example.js. The theme name specifies "light-theme".
3. Try switching between a ThemeContext.Consumer and ThemeConsumer and you can sometimes see the theme log as intended. In the sandbox example, the ThemeConsumer is not working properly. In my private repo, the ThemeConsumer works but the ThemeContext.Consumer doesn't work properly. 

## Expected Behavior
Theme consumer should be in sync with it's next closest parent provider.

## Your Environment
| Tech    | Version |
| ------- | ------- |
| Base UI | v9.52.1  |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by chasestarr** [comment]
The problem here arises from how the baseui package includes multiple module types. Imports from the root `baseui` package are `esm`, and we've also set up first-level imports to default to the same `baseui/style`.  Where this gets inconsistent is when you need to import any deeper. For example, an import from `baseui/style/theme-provider.js` is commonjs. 

There are two options to resolve, either import `ThemeConsumer` from the first-level or import `ThemeContext` from `baseui/esm/style/theme-provider.js`.
