### ISSUE TITLE
Update Popper to v2

### ISSUE THREAD

**Issue by nicolad** [uber/baseweb#3244]
- I've created a bug report since I didn't have any other way to relate an outdated package.
- The warning I am getting is following:
```
warning baseui > popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
```

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.71.0  |
| React   |  16.13.1 |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by FezVrasta** [comment]
Popper maintainer here, just for your information, we provide a migration guide to help upgrade from v1 to v2:

https://popper.js.org/docs/v2/migration-guide/

The advantages of the new major version are a lot:

- Smaller bundle size (3kb for the base lib, vs 7kb of v1);
- Smarter defaults;
- Better offset parents detection (no need to override the boundaryElement option anymore);
- A ton of bug fixes;

**Comment by sandgraham** [comment]
Hi @nicolad, the only real blocker for us on this is that we are not slated to release a major version until late this year. To bump this dependency right now we would need to make sure it does not break any of our own API, otherwise it will have to wait until v10 around September.

We would certainly welcome a PR if you find that it can be done without a breaking change though! Let me know if you are interested and would like any guidance on contributing.
