### ISSUE TITLE
Popover is not appearing if anchor component does not forward ref

### ISSUE THREAD

**Issue by hhvys** [uber/baseweb#3265]
## Feature description
Popover should not be dependent on attributes of child component.

Check 2 examples in the codesandbox for better understanding
https://codesandbox.io/s/statefulpopover-56pd9?file=/example.js

**Comment by hhvys** [comment]
A possible workaround is to wrap anchor element with a container in Popover itself. 

I don't whether doing this will break any styles for consumers or not.

**Comment by devanshj** [comment]
We need the anchor ref (and hence the dom element) because we pass it while creating a `Popper` instance
https://github.com/uber/baseweb/blob/531544c401b5a601d290eb4a0228626359688bac/src/layer/tether.js#L73

As a matter of fact there's also a warning when the ref doesn't get set
https://github.com/uber/baseweb/blob/531544c401b5a601d290eb4a0228626359688bac/src/layer/tether.js#L47-L55

In the scenario in your sample, React bails out due to an error so the warning doesn't get logged and I've sent a PR to fix that.

**Comment by chasestarr** [comment]
There's an error logged on initial load of the codesandbox example (shown below).

**Comment by devanshj** [comment]
I agree on the part that forwarding ref is a must and is the users responsibility. But the error is on our expense that we blindly (clone and) render a non ref forwarding functional component with a ref, it would be better to log an error/warning that tells the user to use forwardRef because it's _our_ requirement.
