### ISSUE TITLE
[Menu] Keyboard events must bubble for menu key navigation to work

### ISSUE THREAD

**Issue by airhorns** [uber/baseweb#3557]
Right now, `<Menu/>` attaches keyboard events to the document in order to implement moving the focused menu item around. This means that if any parent component wants to stop the propagation of the event, it can't, without breaking the Menu functionality. A parent component might want to stop the propagation of the event because there are other grandparents also listening for events.

Imagine a `<Menu/>`, or more realistically a `<Select/>`, inside a popover that opens up from another thing that is keyboard navigable, like a tree, or a canvas of draggable components, or whatever. The outer component system might listen for keyboard events too, and when you press a key that both systems are listening for, the user would expect that only one should respond. The normal way to accomplish this would be to have some container for the inner component listen for the event and then call `event.stopPropagation()` on it, so that it didn't bubble out and trigger the outer navigation component's behaviour as well.

But, `<Menu/>` needs its events to make it all the way to the [document](https://github.com/uber/baseweb/blob/master/src/menu/stateful-container.js#L83) for them to be acted on. This means `<Menu/>`s and `<Select/>`s nested inside anything that are also listening to keyboard events either don't work or trigger both behaviours.

## Current Behavior

Menu keyboard navigation doesn't work if keyboard event are `stopPropagation`'d anywhere along the chain to the document, which might be necessary to prevent double keyboard navigation behaviours in nested trees

## Expected Behavior

Menu keyboard navigation should work if an ancestor `stopPropagation`s. It should be able to do this by attaching keyboard event listeners to container nodes inside the `<Menu/>`, instead of on the document.

## Context

AFAICT there is a good reason `<Menu/>` works the way it does surrounding nested menus responding properly to keyboard events, but I am not deeply familiar with the issue at hand. Maybe @chasestarr could shed some light on why it was necessary to attach listeners to the document, and perhaps we could puzzle out a solution to that issue that keeps the event listeners local to the `<Menu/>` so that they don't require full propagation! 

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | 9.90.0 |
| React   |  16.13.1   |
| browser | Chrome latest  |

- [X] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by chasestarr** [comment]
It's been a bit since working on the feature, but my guess it was just some continuation of a naive proof-of-concept. After some quick prototyping adding a keydown listener to the root list element works after some testing for menu. It's currently broken for the select component though https://github.com/uber/baseweb/pull/3558

**Comment by airhorns** [comment]
Looks like #3631 might address this too for anyone following along

**Comment by jiaoy14** [comment]
"Menu keyboard navigation doesn't work if keyboard event are stopPropagation'd anywhere along the chain to the document, which might be necessary to prevent double keyboard navigation behaviours in nested trees"

 @airhorns Could you please help reproduce this example? I try to reproduce it but fail.

**Comment by airhorns** [comment]
I too struggled to reproduce this! Figured it out though, here's a reproduction where the top element has a .stopPropagation call in a parent and the bottom element doesn't: https://stackblitz.com/edit/react-hcwvyo?file=src/index.js

The key bit in why this example is broken is that it is using React `17.0.0-rc.0` which I was also using locally when I encountered this issue! And, it super makes sense because of https://reactjs.org/blog/2020/08/10/react-v17-rc.html#changes-to-event-delegation , which would mean that event propagation stops at the render root, not the document, but only in React >= 17 or the experimental versions.

**Comment by jiaoy14** [comment]
Very appreciate your example and thanks for your blog @airhorns . 

Here is another example: https://stackblitz.com/edit/react-hcwvyo-2urmsk?file=src/example.js.

We don't use any `stopPropagation` here. For now if we focus on the container(area outside the `menu`), only father component will react with keyboard behavior . This is because https://github.com/uber/baseweb/blob/e8f95c91498fbbc023a41f29ca6159fd6ca5d5c1/src/menu/stateful-container.js#L82 we only add listener for `menu` when it is focused. And if we focus on the `menu` ,both `menu` and its father will react. This is the current logic of our master branch. 

So what do you expect us to improve? The thing baseweb cannot do for now is : when we focus on 'menu' , only 'menu' react and its father doesn't react. You may want this?

**Comment by houmark** [comment]
I can confirm this by testing React 17 RC, that event propagation is broken. Enter on `<Select />` no longer works.

**Comment by airhorns** [comment]
@houmark on which baseui version? If it's `master`, #3631 has since landed which means there may be another issue afoot!

**Comment by houmark** [comment]
I was on 9.95.2, but I'll try out master to verify if this is fixed with #3631. I'll report back here later.

**Comment by houmark** [comment]
Sorry, still unable to get baseui installed for development locally. I've tried cloning and npm linking my project but my project fails to start with the following error:

`Module not found: Can't resolve 'baseui' in '/Folder/username/Folder/project/src'`

The contributing guide is a bit weak on this part, and I'm afraid I don't have more time to try things here. It would really be nice with a bit more content added to the guide, so it's easier to kick off. I did run the `yarn documentation:dev` in the cloned baseui folder and while that worked, it seemed really slow.

**Comment by chasestarr** [comment]
Thanks for investigating further everyone. I imagine there will be more issues as a result of updating to the react 17 release candidate. I created a new issue to track any related issues because (I believe) this particular bug has been fixed. Testing process would likely include cloning the baseui repo locally, updating to the RC, and running the test suite. Let me know if this issue needs to be re-opened

**Comment by houmark** [comment]
I did a casual manual test of `Select`'s and our entire web app in React 17-RC1 and the `Select` problem seems to be fixed. Until now I have not found any other issues with Baseweb in React 17.

**Comment by airhorns** [comment]
@houmark there's also this issue with Baseweb checkboxes https://github.com/uber/baseweb/issues/3476 . It's actually React bug, not a Baseweb bug, but I'm not sure if it's in 17-RC1 or just the experimental releases, and it only affects Concurrent mode if you're using that.
