### ISSUE TITLE
[DatePicker] displays wrong date when formatted as d.M.yyyy

### ISSUE THREAD

**Issue by janjaromirhorak** [uber/baseweb#3789]
## Current Behavior
When a `formatString` attribue is set to `d.M.yyyy` and no `mask` attribute is provided, the date `2020/09/25` is displayed as `2.5.9202` instead of `25.9.2020`. When the `mask` attribute is explicitly set to `null`, the date is displayed correctly.

## Expected Behavior
The date should be displayed as `25.9.2020` when no `mask` attribute is provided.

## Your Environment
Tech | Version
-- | --
Base UI | 9.101.0
React | 16.13.1
browser | Firefox 80.0.1

[Minimal working example on Stackblitz](https://stackblitz.com/edit/react-zzmu2a?file=src/example.js)

Source code for the example:
```javascript
import * as React from 'react';
import {DatePicker} from 'baseui/datepicker';

export default () => (
  <DatePicker
    value={[new Date(2020, 8, 25)]}
    formatString="d.M.yyyy"
  />
);
```
- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by MihirGH** [comment]
From the code, I can see that, if the `mask` from the props to DatePicker is non-null (undefined also works) then the `mask` that gets passed to the react-input-mask is computed inside DatePicker via replacing all the letters by 9.

Otherwise if it is null, then the empty string is passed as the mask. 

Should we do the same if the mask from the props is undefined, i.e. sending empty string as the mask if the prop to DatePicker is undefined?

**Comment by MihirGH** [comment]
CC: @gergelyke for the visibility
