### ISSUE TITLE
[Checkbox] Controlled Checkbox fires two events on click when parent controls its state

### ISSUE THREAD

**Issue by AEgan** [uber/baseweb#3847]
Clicking a Checkbox where the parent component controls the state fires two events, and the state remains the same

stackblitz: https://stackblitz.com/edit/react-ypuuaz?file=src/example.js

minimal component:
```jsx
const [checked, setChecked] = React.useState(false);
  return (
    <div onClick={() => setChecked(prev => !prev)}>
      <Checkbox checked={checked} labelPlacement={LABEL_PLACEMENT.right}>
        Sign up for the newsletter
      </Checkbox>
    </div>
  );
```

## Current Behavior

Clicking on the checkbox causes the above `div`'s `onClick` to fire twice with two events. I believe `event.target` for the first event is [this span](https://github.com/uber/baseweb/blob/master/src/checkbox/checkbox.js#L215), the second event.target is [from the input](https://github.com/uber/baseweb/blob/master/src/checkbox/checkbox.js#L224)

Because the function is called twice, attempting to update the state using the code above will result in the state of the `Checkbox` remaining the same.

We can work around this by overriding the Input's `onClick`

```jsx
  const [checked, setChecked] = React.useState(false);
  return (
    <div onClick={() => setChecked(prev => !prev)}>
      <Checkbox
        checked={checked}
        labelPlacement={LABEL_PLACEMENT.right}
        overrides={{
          Input: {
            props: {
              onClick: e => e.stopPropagation(),
            },
          },
        }}
      >
        Sign up for the newsletter
      </Checkbox>
    </div>
  );
```

## Expected Behavior

the parent's `onClick` is only called once per click

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.102.0  |
| React   | 16.14, 17.0   |
| browser |   mac os  |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by sandgraham** [comment]
The issue is that we nest the input inside of a `label` (the `Root` is actually a label). From [mdn](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label):
```
When a <label> is clicked or tapped and it is associated with a form control,
the resulting click event is also raised for the associated control.
```
So the label triggers a second click event on the `checkbox`, which is what ends up bubbling to your parent `div` and causing a second call. I made an [example here](https://codesandbox.io/s/cool-fermat-3b2pv?file=/src/App.js) to showcase the difference with/without a parent `label`.

Normally I wouldn't vote for adding `e.preventDefault`, but since the checkbox is hidden & controlled I think we can add that in as a default to open up this use case.

Thanks for raising the issue, I'll put up a PR in a bit.
