### ISSUE TITLE
[List] MenuAdapter does not forward overrides

### ISSUE THREAD

**Issue by chasestarr** [uber/baseweb#3986]
See this sandbox https://codesandbox.io/s/base-web-menu-with-profile-menu-forked-v704t?file=/src/example.js

I'd like to customize root overrides, but the menu adapter does not forward the overrides through

**Comment by sladjanstojcic** [comment]
I can confirm this bug, just run into it. Solved it like this having custom component until the bug is resolved: 
`const defaultOverrides = (props) => ({
    Root: {
        props: { onMouseEnter: props.onMouseEnter, onClick: props.onClick },
        style: ({ $theme }) => ({
            backgroundColor: props.$isHighlighted
                ? $theme.colors.menuFillHover
                : null,
            cursor: props.$disabled ? 'not-allowed' : 'pointer',
        }),
    },
});

const HVMenuAdapter = React.forwardRef((props, ref) => {
    const mergedOverrides = mergeOverrides(defaultOverrides(props), props.overrides);

    return (
        <ListItem
            ref={ref}
            sublist={props.sublist || props.$size === 'compact'}
            artwork={props.artwork}
            artworkSize={props.artworkSize}
            endEnhancer={props.endEnhancer}
            overrides={mergedOverrides}
        >
            {props.children}
        </ListItem>
    );
});

HVMenuAdapter.displayName = 'HVMenuAdapter';

export default HVMenuAdapter;`
