### ISSUE TITLE
Automatically highlight first item in creatable multi Select

### ISSUE THREAD

**Issue by ksnyder9801** [uber/baseweb#4098]
## Feature description
We are using Select with `creatable`, `multi` and empty `options` as a multiple-value entry. This works great except that pressing Enter to add the typed value "appears" to randomly do nothing (or worse, submit the parent `<form>` without the typed value).

For our use case, ideally, typing into Select's input box would always highlight either the last selected option (if it's still there) or the most relevant option, so hitting Enter would select it.

Two things prevent this and cause the unexpected behavior
1. onMouseLeave removes the highlight

- This is [Menu's](https://github.com/uber/baseweb/blob/v9.110.0/src/menu/stateful-container.js#L331) fault, and I think the behavior probably makes more sense for a "context menu" triggered on click, but not Select's dropdown.

2. "No results" removes the highlight
- This is also due to code in [Menu](https://github.com/uber/baseweb/blob/v9.110.0/src/menu/stateful-container.js#L117). [Repro](https://codesandbox.io/s/gmv9c?module=src/example.js&file=/src/example.js): Type abc, enter (works), type abcd, enter (doesn't work). The second time you type "abc", there are "No results", removing the highlight before you type "d". This is pretty common if you are entering several values with a shared prefix (numbers, identifiers...)

Propose adding a new prop `autoHighlightFirstItem` (to both Select and Menu) for this, unless you think that we can change the default behavior - then maybe only Menu needs the prop.

**Comment by chasestarr** [comment]
I can't think of a common use-case where not highlighting the first available element would be a downside, so updating the default in Select makes sense to me. As for Menu, auto highlighting should be configurable so that nested menu navigation is maintained. Specifically, navigating through the primary menu should not immediately navigate through the secondary menu when it opens. (below is an image of what I would prefer not happen, focus should continue to be on the primary menu)

![child-menu-navigation](https://user-images.githubusercontent.com/5317799/109554095-a8bc8480-7a88-11eb-915c-751810c086f5.png)
