### ISSUE TITLE
Unable to override Item component for Rating 

### ISSUE THREAD

**Issue by niksmac** [uber/baseweb#4318]
Reproduce the issue here https://codesandbox.io/s/c2ko6

## Current Behavior

When I tried to override the component for Rating component I am not able access the props. 

```jsx 
<StarRating
  value={5}
  onChange={({ value }) => onChange(value)}
  numItems={11}
  inputRef={ref}
  overrides={{
    Root: {
      component: ({ children }) => (
        <div
          className="flex flex-row gap-1 md:gap-3 w-full justify-between"
          role="radiogroup">
          {children}
        </div>
      )
    },
    Item: {
      component: ({ $index, $isSelected, $isActive }) => (
        <div
          key={$index}
          role="radio"
          className={`border-2 rounded-sm border-gray-200 items-center justify-center hover:border-green-400 cursor-pointer text-sm md:text-base text-center p-1 md:p-2 w-1/12 md:w-full ${
            $isSelected ? 'nps active' : 'nps'
          }`}>
          {$index - 1}
        </div>
      )
    }
  }}
/>
```

## Expected Behavior

I should get the clicked values/indexes in submission

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.107.0  |
| React   |     16.x    |
| browser |         |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by lextas** [comment]
Since you override the `Item`  you are also responsible for adding the behavior. The data doesn't change because you have `value={5}` which does not respond to the value you expect from `useState`.

If you change the value to `value={value}`  and you add an `onClick={() => setValue($index)}`  to the `Item` it works as expected. I don't see any issues then.

Updated your example: https://codesandbox.io/s/base-web-starrating-forked-w3d9n?file=/src/example.js

**Comment by niksmac** [comment]
That solved my issue, thanks.
