### ISSUE TITLE
Input components don't style disabled state when it set via <fieldset disabled> 

### ISSUE THREAD

**Issue by gevgeny** [uber/baseweb#4392]
If a checkbox is disabled via `<fieldset disabled>` its style is not updated.
```jsx
<fieldset disabled>
    <Checkbox>
      Sign up for the newsletter
    </Checkbox>
</fieldset>
```
Here is the demo with comparing of the Checkbox component and native HTML checkbox https://codesandbox.io/s/base-web-checkbox-forked-7xfyn?file=/src/example.js:200-653

**Comment by williamernest** [comment]
Thanks for filing this issue. This is an edge case that will likely not get implemented as there are plenty of workarounds to solve this issue (adding disabled onto the checkbox or creating your own fieldset component that manages setting the child element state). Component state is already complex enough without trying to figure out a native html ancestor elements state.

**Comment by gevgeny** [comment]
I would not say that it is an edge case, it is a very common practice to disable a whole form while it is sending. And as for component `disabled` state, it is inherited from ancestor now anyway, and it is disabled already, it is just style which is not consistent to the state.

**Comment by williamernest** [comment]
I would disagree in considering this is an edge case. Since react offers a trivial way around this issue, and replicating this behavior doesn't really offer a lot of value (outside of being semantically aligned with the fieldset element). 

The component is not disabled in this instance, the parent is preventing any interactions with the child elements. The state of the checkbox is disabled=false and checked=false.  The component is inheriting nothing in this instance, as the parent element is swallowing the event. 

Since we're using a react, the workaround is adding disabled to the checkbox whenever you set disabled on the fieldset which is trivial to implement.

**Comment by williamernest** [comment]
Closing this issue as we don't have plans to implement support for this feature.
