### ISSUE TITLE
Layout Grid Margin Clarity

### ISSUE THREAD

**Issue by ProjectBarks** [uber/baseweb#4443]
It is unclear to me what this calculation is supposed to be doing: [src/layout-grid/styled-components.js#L111
](https://github.com/uber/baseweb/blob/570b0c01a9c6c4d0b582baf7949e0c85c4ee3f5b/src/layout-grid/styled-components.js#L111). 
```
            paddingLeft: `${getResponsiveNumber($gridGutters, idx) /
              2}${$gridUnit}`,
            paddingRight: `${getResponsiveNumber($gridGutters, idx) /
              2}${$gridUnit}`,
```
I am just trying understand what the purpose of this is? My immediate intuition is that either the margin should always increase the padding on the container or there should be no outer gap on the outside edge and margin is the only way to affect inner gap. I was hoping to get some clarity on this design decision? 

## Current Behavior
It subtracts the two numbers, divides by two, then subtracts by 0.5.

## Expected Behavior
Unknown

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v10.0.0  |
| React   |         |
| browser |         |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by williamernest** [comment]
Hey Brandon, thanks for the question. The logic you pointed to calculates the size of the gutters between each cell in our layout grid. It references the theme variables in [themes/shared/grid.js](https://github.com/uber/baseweb/blob/570b0c01a9c6c4d0b582baf7949e0c85c4ee3f5b/src/themes/shared/grid.js) and divides those values by 2 (since padding-right of one cell and padding-left of another cell will be combined to add up to the desired gutter of the grid). As for the logic this is contained within, if you look at the mediaQueries reducer at the [top](https://github.com/uber/baseweb/blob/570b0c01a9c6c4d0b582baf7949e0c85c4ee3f5b/src/layout-grid/styled-components.js#L82) you'll see that each index value represents a different sized screen/media query. So for smaller screens, we use smaller gutters and less columns, etc. As the screen size gets larger we adjust the layout to fit more on the screen (hence the responsive nature).
