### ISSUE TITLE
Animation pattern for custom components

### ISSUE THREAD

**Issue by nrakochy** [uber/baseweb#4661]
Hi there,

Thanks for the great library. Do you have any recommended patterns for applying animations to custom components w/ Baseweb?

That is, using the styled pattern on a div. Or, conversely, if there was an Animation component itself.

I see available keys on the animations theme object, as well as the popover implementation, which looks rather specific to that component. 

any insight would be appreciated. Thanks!

**Comment by williamernest** [comment]
We provide most of our animations as theme properties, but we don't have a specific animation library/component that completely handles them. Usually, handling animations in a generic way leads to a lot of bloat (either with code or performance limitations due to the nature of generic implementations). Happy to assist if you have a specific thing you're trying to do if you want to start off with a code sandbox. 

Framer is a great library, as well as React Motion and Remotion.

**Comment by nrakochy** [comment]
Okay great I appreciate the feedback. Couldn't grok if there was an embedded patterns. Thanks!
